name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs_on: ubuntu_lastes
      spteps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Lint
          run: npm run lint
        - name: Test code
          run: npm run test
        - name: Biuld code
          run: npm run build
        - name: Deploy code
          run: echo "Deploying... "